# Generated by Django 4.0 on 2021-12-21 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_streamplatform_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wishlist.streamplatform'),
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='url',
            field=models.URLField(),
        ),
    ]
