# Generated by Django 4.0 on 2021-12-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_alter_wishlist_platform_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='platform',
            new_name='wishlist',
        ),
    ]
